FROM python:3.7-slim

#RUN mkdir /app
#
#COPY ./api_yamdb/ /app
#
#RUN pip3 install -r /app/requirements.txt --no-cache-dir
#
#WORKDIR /app

WORKDIR /app

COPY . .

RUN ls

#RUN pip3 install -r requirements.txt --no-cache-dir

#CMD ["gunicorn", "api_yamdb.wsgi:application", "--bind", "0:8000" ]
